name: RDP Connection via ngrok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    timeout-minutes: 350
    steps:
    - name: Set up ngrok
      uses: cyb3rking/ngrok-rdp-action@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        username: 'runneradmin'
        password: '12345678'
        
    - name: Display Connection Info
      run: |
        echo "### 💻 RDP Connection Details" >> $GITHUB_STEP_SUMMARY
        echo "Please use the following details to connect via RDP:" >> $GITHUB_STEP_SUMMARY
        echo "- **Address:** The address and port will be available in the 'Set up ngrok' step logs." >> $GITHUB_STEP_SUMMARY
        echo "- **Username:** runneradmin" >> $GITHUB_STEP_SUMMARY
        echo "- **Password:** YourSecurePasswordHere" >> $GITHUB_STEP_SUMMARY

